#!/bin/bash

echo "Copying configuration files"
cd ~/repos/rice
cp -r ~/.config/i3/ i3/
cp ~/.config/i3status/config i3status/config
cp ~/.config/ranger/rc.conf ranger/rc.conf
cp ~/.config/images/wallpaper.jpg images/wallpaper.jpg
cp ~/.config/images/lockscreen.png images/lockscreen.png
cp -r ~/.config/polybar polybar
cp ~/.bashrc bashrc
cp /etc/vimrc global-vimrc
cp ~/.vimrc vimrc
cp ~/.Xresources Xresources
cp ~/.config/compton.conf compton.conf
cp /usr/bin/ricepush ricepush
yay -Q | cut -f1 -d " " > programs.txt
echo "Updating README.md"
vim README.md
echo "Adding files to git repository"
git add --all
echo "Committing changes"
git commit
echo "Uploading to github"
git push origin master
echo "Done uploading to github"
